### ISSUE TITLE
Include instructions for simple installation

### ISSUE THREAD

**Issue by jfsiii** [rhelmer/graphs#1]
The steps for hosting your own data (MySQL, etc) are described but the simple "just make one directory and then use the Mozilla data" approach is only described in [the blog post](http://roberthelmer.com/blog/?p=185)

Perhaps all the information from that post should make it into the repo somewhere.

**Comment by rhelmer** [comment]
Good point thanks :)
I also added a note about the Vagrant setup, since I think that's non-obvious too:
https://github.com/rhelmer/graphs/commit/14198c3f2f853e000b1e8c6d5eb52bb000888ee2
